set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports ser_data_out]
set_property IOSTANDARD LVCMOS33 [get_ports ser_data_out_en_disp]


set_property IOSTANDARD LVCMOS33 [get_ports MTDS_SPI_Out_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports MTDS_SPI_Out_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports MTDS_SPI_Out_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports MTDS_SPI_Out_ss_io]
set_property PACKAGE_PIN D14 [get_ports MTDS_SPI_Out_ss_io]
set_property PACKAGE_PIN H14 [get_ports MTDS_SPI_Out_sck_io]
set_property PACKAGE_PIN F16 [get_ports MTDS_SPI_Out_io0_io]
set_property PACKAGE_PIN G16 [get_ports MTDS_SPI_Out_io1_io]
set_property PACKAGE_PIN C4 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN D4 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN C17 [get_ports ser_data_out]
set_property PACKAGE_PIN H17 [get_ports ser_data_out_en_disp]
set_property PACKAGE_PIN E3 [get_ports clk_100MHz]
set_property PACKAGE_PIN P17 [get_ports reset_rtl_0]
