# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led_appl_constraints.xdc

# Block Designs: bd/design_led_appl/design_led_appl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl || ORIG_REF_NAME==design_led_appl} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_microblaze_0_0/design_led_appl_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_microblaze_0_0 || ORIG_REF_NAME==design_led_appl_microblaze_0_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_dlmb_v10_0/design_led_appl_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_dlmb_v10_0 || ORIG_REF_NAME==design_led_appl_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_ilmb_v10_0/design_led_appl_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_ilmb_v10_0 || ORIG_REF_NAME==design_led_appl_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_dlmb_bram_if_cntlr_0/design_led_appl_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_led_appl_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_ilmb_bram_if_cntlr_0/design_led_appl_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_led_appl_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_lmb_bram_0/design_led_appl_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_lmb_bram_0 || ORIG_REF_NAME==design_led_appl_lmb_bram_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_xbar_0/design_led_appl_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_xbar_0 || ORIG_REF_NAME==design_led_appl_xbar_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_microblaze_0_axi_periph_0/design_led_appl_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_led_appl_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_microblaze_0_axi_intc_0/design_led_appl_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_led_appl_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_microblaze_0_xlconcat_0/design_led_appl_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_led_appl_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_mdm_1_0/design_led_appl_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_mdm_1_0 || ORIG_REF_NAME==design_led_appl_mdm_1_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_clk_wiz_1_0/design_led_appl_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_clk_wiz_1_0 || ORIG_REF_NAME==design_led_appl_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_rst_clk_wiz_1_100M_0/design_led_appl_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_led_appl_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_axi_uartlite_0_0/design_led_appl_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_axi_uartlite_0_0 || ORIG_REF_NAME==design_led_appl_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_axi_gpio_0_0/design_led_appl_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_axi_gpio_0_0 || ORIG_REF_NAME==design_led_appl_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_axi_gpio_1_0/design_led_appl_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_axi_gpio_1_0 || ORIG_REF_NAME==design_led_appl_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_led_driver_0_0/design_led_appl_led_driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_led_driver_0_0 || ORIG_REF_NAME==design_led_appl_led_driver_0_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_led_ram_0_0/design_led_appl_led_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_led_ram_0_0 || ORIG_REF_NAME==design_led_appl_led_ram_0_0} -quiet] -quiet

# IP: bd/design_led_appl/ip/design_led_appl_PmodMTDS_0_0/design_led_appl_PmodMTDS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_led_appl_PmodMTDS_0_0 || ORIG_REF_NAME==design_led_appl_PmodMTDS_0_0} -quiet] -quiet

# XDC: bd/design_led_appl/design_led_appl_ooc.xdc
